#!/bin/bash

set -eu

out_dir=../raw_data
cd scripts

while true; do
    now=$(date --utc --iso=min)
    # get data
    ./monitor_replication.py -l $out_dir/$now.log --nocompare \
        rw_v2.ini ro_v2.ini \
        >$out_dir/$now.out
    # post that data
    ./monitor_replication.py -l $out_dir/$now.log --quiet --process --record-data \
        $out_dir/$now.out
    echo "$now posting complete"
    sleep 1800
done

